// ==============================================================
// 靜態資料庫 (店家清單)
// ==============================================================
const STORE_LIST = [
    {code: 'oza2', name: '義庭Eating'}, {code: '12si', name: '巴酣酣小吃店'}, {code: 'vwab', name: '合品廣東粥鍋燒麵'}, {code: 'g3ya', name: '胖老爹美式炸雞 (大園中正東店)'},
    {code: 'nzii', name: '大樹藥局 (大園中正店)'}, {code: 'tlmk', name: '全聯福利中心 (大園華興店)'}, {code: 'nyyn', name: '合浦刀切麵食工坊 (大園中正店)'},
    {code: 'r5wu', name: '統一超商 (桃園玉興店)'}, {code: 'uqwd', name: '大園古早味'}, {code: 'o0lk', name: '家味小館'}, {code: 'fn3n', name: '點一點早午餐'},
    {code: 'lbpm', name: '吳家早點'}, {code: 'nvtx', name: '宮後多食'}, {code: 'r3af', name: '緣生緣速食早餐店 (桃園新生店)'}, {code: 'mero', name: '亞提斯早午餐'},
    {code: 'f4xf', name: '合浦刀切麵食工坊 (大園大觀店)'}, {code: 's6xw', name: '藤哥五星級便當牛排'}, {code: 'bg2a', name: '小木屋鬆餅 (大園中華店)'},
    {code: 'achw', name: '蕪茗小吃店'}, {code: 'chfq', name: '姆加塔泰式料理'}, {code: 'dm90', name: '朋有小吃店'}, {code: 'f7me', name: 'STARBUCKS 星巴克 (大園華興門市)'},
    {code: 'cd4m', name: '李記南台灣鱔魚麵 (桃園大園店)'}, {code: 'hc7z', name: '城市漢堡 (大園大觀店)'}, {code: 'a-xk', name: 'KFC (桃園大園)'},
    {code: 'o4nz', name: '統一超商 (桃園園山店)'}, {code: 'h6ec', name: '錢糖潮'}, {code: 'edum', name: '65鴨肉羹'}, {code: 'z59p', name: '歐蕾早午餐'},
    {code: 'hozw', name: '胖叔叔日式炸物'}, {code: 'tmzs', name: '全家便利商店 (大園大工店)'}, {code: 'axte', name: 'CoCo都可 (大園大工店)'},
    {code: 'g4vi', name: '北一麵飯館'}, {code: 'z43p', name: '早安！美之堡早餐 (大園店)'}, {code: 'urip', name: '八廚職人弁当 (大園新生店)'},
    {code: 'f7wl', name: '夠in咖啡 (大園新生店)'}, {code: 's7s1', name: '斑馬原味茶'}, {code: 'efok', name: '迷客夏Milksha (桃園大園客運店)'},
    {code: 'fg22', name: '肯德基KFC炸雞廚房 (桃園大園店)'}, {code: 'f9nk', name: '甲一飯包 (桃園大園店)'}, {code: 'fyvl', name: '一鍋一食'},
    {code: 'iocs', name: '全家便利商店 (大園蓮園店)'}, {code: 'py86', name: '北港肉羹麵食館'}, {code: 'olcp', name: '小龍湯包'}, {code: 'v5ib', name: '茶聚 (大園和平店)'},
    {code: 'idg4', name: 'CoCo都可 (桃園大園店)'}, {code: 'ph5m', name: '九大魯肉飯雞肉飯 (大園店)'}, {code: 'g4s7', name: '一起早餐吧'},
    {code: 'jow9', name: '得正 OOLONG TEA PROJECT (桃園大園計劃)'}, {code: 'lf5s', name: '阿江蚵仔大腸麵線'}, {code: 'vbdh', name: '大園鵝肉店'},
    {code: 'xn15', name: '元爵味黃燜雞米飯 (大園中正東店)'}, {code: 'f7ni', name: 'Pizza Hut必勝客 (桃園大園店)'}, {code: 'mlqg', name: '清心福全 (桃園大園中華店)'},
    {code: 'rgfr', name: '阿里山畚箕湖鐵路便當 (桃園大園店)'}, {code: 'l0bl', name: '麥當勞(S244 大園中正店)'}, {code: 'f24n', name: '萬波島嶼紅茶 (桃園大園店)'},
    {code: 'a-ravk', name: '桃園大園店(新)(萬波島嶼紅茶Wanpo Tea Shop/展帛)'}, {code: 'kmcp', name: '丫翔涼麵'}, {code: 'cgzn', name: 'CoCo都可 (大園中正東店)'},
    {code: 'f5ch', name: '麥町吐司工房 (大園華興店)'}, {code: 'g3ki', name: '85度C (大園中山店)'}, {code: 'g3ox', name: '祥祥炒飯功夫館'},
    {code: 'k0ck', name: '康是美 COSMED'}, {code: 'qg4e', name: 'COMEBUY (大園中正東店)'}, {code: 'r5zu', name: '統一超商 (桃園航園店)'},
    {code: 'w24k', name: '來來蒜味肉羹'}, {code: 'dek7', name: '2派克脆皮雞排 (桃園大園店)'}, {code: 't1oa', name: '莎纋莉手工營養三明治 (民生南店)'},
    {code: 'ay1e', name: '哈囉早午餐Hello Brunch (桃園大園店)'}, {code: 'p5em', name: '二堂頭銷魂鴨肉飯 (桃園大園店)'}, {code: 'cd5k', name: '小莊手工湯包'},
    {code: 'omiv', name: '五桐號 WooTEA (桃園大園店)'}, {code: 'iw15', name: '巧市代廣東粥'}, {code: 'jpc5', name: '思茶 (桃園大園店)'},
    {code: 'niht', name: '老先覺功夫窯燒鍋 (桃園大園店)'}, {code: 'r6nl', name: '赤月燒餃子 & 丰丼食堂'}, {code: 'w38e', name: '呷咪 (大園)'},
    {code: 'x2ir', name: '潮味決·湯滷專門店 (桃園大園分社)'}, {code: 'cpsv', name: '龜記茗品 (大園中山店)'}, {code: 'rg1z', name: '銅心鍋燒麵'},
    {code: 'hm79', name: '老全大腸蚵仔麵線 (大園總店)'}, {code: 'we52', name: '全家便利商店 (大園帝景店)'}, {code: 'f3ya', name: 'Soker steak熟客牛排店'},
    {code: 'm2ts', name: '台北麻將麻辣臭豆腐 (桃園大園店)'}, {code: 'a35p', name: '可不可熟成紅茶 (大園中山北店)'}, {code: 'd8a2', name: '鳳記手工湯包'},
    {code: 'htr2', name: '醒了才煮'}, {code: 'jp68', name: '清心福全 (大園大觀店)'}, {code: 'kl4w', name: '脆皮雞'}, {code: 'pdpi', name: '那間早午餐 a brunch store'},
    {code: 'wm6s', name: '健康燒腊'}, {code: 'xtmr', name: '全聯福利中心 (大園和平店)'}, {code: 'yqf5', name: '巧味大腸包小腸'},
    {code: 'lzzj', name: '林三茶研所 (桃園大園店)'}, {code: 'wr5x', name: '小駱家麻奶鍋 (大園中華店)'}, {code: 'ge3f', name: '茶湯會 (大園仁壽店)'},
    {code: 'u2as', name: '珍煮丹 (桃園大園店)'}, {code: 'dg4q', name: '呷鍋 (大園店)'}, {code: 'ksfx', name: '吮指王KING (大園和平西店)'},
    {code: 'bk9v', name: '麥味登 (大園大觀店)'}, {code: 'eqmv', name: '心海越南美食'}, {code: 'h85v', name: '酥麻雞蛋仔'}, {code: 'ryi6', name: '明仁二代目章魚燒 (大園店)'},
    {code: 's9eb', name: '阿嬤的麻油雞酒飯'}, {code: 'q312', name: '雞雞傳說'}, {code: 'f0em', name: '鮮茶道 (大園中正東店)'},
    {code: 'grtl', name: 'cama café (桃園大園店)'}, {code: 'prqp', name: '肯德基KFC炸雞漢堡店 (桃園大園店)'}, {code: 'v2zp', name: '傻師傅湯包 (大園民生南店)'},
    {code: 'vmd3', name: '祐桑一口煎餃'}, {code: 'x6ha', name: '好了啦紅茶冰 (大園新生店)'}, {code: 'd7u3', name: '串癮串烤'},
    {code: 'h3on', name: 'NU PASTA (桃園大園店)'}, {code: 'hdq3', name: '李師傅日式簡餐快炒'}, {code: 'r69k', name: '肯德基KFC漢堡(紙包雞飯)專賣店(桃園大園店)'},
    {code: 'ft5h', name: '東北秘製滷味'}, {code: 'uke6', name: '玉将食堂'}, {code: 'c4cg', name: '天天來放山雞鵝肉飯麵館'}, {code: 'p6uz', name: '肯得利香雞排'},
    {code: 'f6jv', name: '清心福全 (大園中正東店)'}, {code: 'zycw', name: '黃金稻職人炒飯 (大園新興店)'}, {code: 'kn29', name: '老闆好會炒 (Lao Ban Hao Huei Chao)'},
    {code: 'vq10', name: '桶一天下 (桃園大園店)'}, {code: 'j5ve', name: '好停車宵夜早餐店'},
    {code: 'p5yp', name: '元鴨坊益身當歸鴨'}, {code: 'j3ox', name: '高品味轉角美食'}, {code: 'g7r3', name: '紅豆之家'}, {code: 'li3v', name: '鍋賣局(桃園大園店)'},
    {code: 'xjoj', name: '吳記燒麻糬(桃園大園店)'}, {code: 'f2st', name: '曼谷小館(桃園大園店)'}, {code: 'zl5t', name: '小六の鍋'}, {code: 'y4hv', name: 'Mowan港式串烤雞蛋仔'},
    {code: 'okmc', name: 'Watstons屈臣氏(大園店S0267)'}, {code: 'u9zj', name: '大園豆花'}, {code: 'khtt', name: '粥日興鍋燒麵'}, {code: 'tv7h', name: '陳記臭家莊清蒸麻辣臭豆腐'},
    {code: 'evot', name: '品安炸雞(桃園大園店)'}, {code: 'auuf', name: '左撇子義式廚房'}, {code: 's1b2', name: '屢品鮮鵝肉(桃園大園店)'}, {code: 'qwtw', name: '小北百貨(大園店)'},
    {code: 'ovpb', name: '咖竅咖啡'}, {code: 'u6vo', name: '玉津咖啡(大園中山店)'}, {code: 'dv0k', name: '木昂手作(大園新生北店)'}, {code: 'bayg', name: '拿坡里(大園店8223)'},
    {code: 'q988', name: '郭老爹食堂'}, {code: 'lsi3', name: '三顧茅廬(大園中山南店)'}, {code: 'uifm', name: 'MEET COFFEE'}, {code: 'av85', name: '統一超商(桃園觀群店)'},
    {code: 'f2qa', name: 'Good morning早餐'}, {code: 'eko6', name: '廟口蜜汁燒烤冷飲'}, {code: 'dxt5', name: '大袁小館'}, {code: 'mnf5', name: '植得蔬食'},
    {code: 'pnbe', name: '麥當勞歡樂送(244大園中正)(pandago)'}, {code: 'ji8v', name: '烤地瓜養生鋪'}, {code: 'n4lu', name: '極緻餐舖'}, {code: 'o5vg', name: 'Gotcha鮮饗茶(桃園大園店)'},
    {code: 'u061', name: '三寶大腸麵線'}, {code: 'rmty', name: '秘醬滷味'}, {code: 'ff2s', name: '澎湖風味館'}, {code: 'sih2', name: '儂翠泰式料理(大工路店)'},
    {code: 'r8kj', name: '清原芋圓(桃園大園店)'}, {code: 'of5s', name: '酒米食堂(桃園大園店)'}, {code: 'hfjg', name: '川醉湘(桃園大園店)'}, {code: 't4co', name: '鑫得壽司專賣店'},
    {code: 's3gs', name: '無飲(大園店)'}, {code: 'tgiy', name: '三年愛班豆花冰舖(大園店)'}, {code: 'r5hn', name: '城市漢堡(大園和平店)'}, {code: 'hwrd', name: '巴拉舫小吃店(巴拉舫餐酒館)'}
];